### ISSUE TITLE
Use binascii.unhexlify instead of str.decode

### ISSUE THREAD

**Issue by an0nfunc** [ninnghazad/roccat_kone_aimo#1]
Hey!

Thanks for bringing some much needed love to the Roccat AIMO, hope we'll get this train rolling :)

For Python 3.8 I needed to change `str.decode('hex')` to `binascii.unhexlify("<hex here>")`, since you can only decode bytes now iirc. `binascii.unhexlify` is part of `binascii`, which should be available for your python version as well.

```
Traceback (most recent call last):
  File "/usr/local/bin/aimo.py", line 117, in <module>
    init()
  File "/usr/local/bin/aimo.py", line 110, in init
    data = "0E06010100FF".decode("hex")
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by ninnghazad** [comment]
Changed, close if it's fixed for you.

**Comment by an0nfunc** [comment]
LGTM, thanks!
