### ISSUE TITLE
TypeError in Colors_to_msg function

### ISSUE THREAD

**Issue by enlight3d** [ninnghazad/roccat_kone_aimo#2]
Hey, I was searching for a way to control my mouse colors outside of roccat swarm (integration for Aurora RGB for example) and tried your script.

You have a little error here : 
`msg += "%02x%02x%02x00" % (color[0]*255,color[1]*255,color[2]*255)`

Should be :
`msg += "%02x%02x%02x00" % (int(color[0]*255),int(color[1]*255),int(color[2]*255))`

Anyway it's great ! It does work on linux (unfortunately can't get it to work on windows even when installing libusb drivers for the mouse). Tried to re-implement your code with pywinusb but no luck.

Also, is it normal that the mouse becomes unusable when controlling its lights ? That would totally kill my idea of implementing it in aurora rgb...

**Comment by ninnghazad** [comment]
Well it depends. 
Using the python/libusb version will freeze the mouse for a moment when setting colors - so animations using this method won't work. 
The CPP/hidraw version however should not have this problem and is very fast.
